# Generated by Django 4.0.4 on 2022-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsdQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('euro_rate', models.FloatField()),
                ('real_rate', models.FloatField()),
                ('yen_rate', models.FloatField()),
            ],
            options={
                'verbose_name': 'Cotação do dólar',
            },
        ),
    ]
